### PR TITLE
Cursor.getmulti() initital implementation (#201)

### PR DESCRIPTION
**Pull request by willsthompson**
(Draft PR)

### CODE REVIEW

**Comment by willsthompson** [comment]
Looks like I broke the C build, but I don't have this problem building on my Mac. Do I need to be passing certain flags to clang?

**Comment by jnwatson** [comment]
I'm surprised it compiled. You should be at least getting a warning for that problem.

**Comment by willsthompson** [comment]
It looks like there are two issues: 

1) The CFFI version breaks on a 2.7 build. I'm explicitly checking the Python version in the `getmulti()` to toggle `yield from`, so I don't think this should break at runtime. Are you running a linter in your build? If this is too much of a hassle, I can just remove `yield from` altogether.
2) The C build breaks on Windows. I don't even get a warning from clang, and unless I'm missing something there's no line number in the failed job log, so I'm not sure what to do here.

**Comment by jnwatson** [comment]
Unless we do some fancy preprocessing, you'll need to remove the yield from. The whole file has to parse as 2.7 even if it doesn't execute it. I did just look at futurize, but even it doesn't handle yield from.

Regarding the C build, the Windows MSVC C compiler is very, very old school. You must declare variables at the top of the block. There's no flag I'm aware of to duplicate in clang.

**Comment by willsthompson** [comment]
Okay, I removed yield from syntax. And type casting the arguments to `PyBytes_FromStringAndSize` is what eventually fixed the MSVC build.

**Comment by jnwatson** [comment]
Great. The only thing left is some basic tests. It doesn't have to be complicated at all. We do want a dupfixed, and dupsort non-dupfixed, and a non-dupsort case.

**Comment by willsthompson** [comment]
It looks like the [source data](https://github.com/jnwatson/py-lmdb/blob/master/tests/testlib.py#L137) for the test suite is strictly 1:1 key value pairs. I'll keep it basic, but is it safe to assume I should add some data with multiple values for testing dupsort/dupfixed? Maybe a VALUES2_MULTI that simply creates pairs of empty bytes for each key?

**Comment by willsthompson** [comment]
Tests are passing now

**Review by jnwatson — APPROVED** [review]

**Comment by jnwatson** [comment]
Thank you for your contribution.

**Pull request merged**
