### PR TITLE
Preload the value only if it is going to be used

### PR DESCRIPTION
**Pull request by jnwatson**
Plus a new doc section

### CODE REVIEW

**Comment by ajschorr** [comment]
Sorry if this is a stupid question, but in lmdb/cpython.c/trans_pop(), why is the invocation of preload not enclosed between Py_BEGIN_ALLOW_THREADS and Py_END_ALLOW_THREADS? In every other place where it's called, it is bracketed with those calls. I imagine I'm missing something...

**Comment by dw** [comment]
It's not a stupid question at all, more like a keen eye :)  @jnwatson preload() needs the GIL dropped in order to be useful at all. Sorry I didn't spot that in review

**Comment by dw** [comment]
I _think_ it wants to be moved into `_cursor_get_c`, but may be mistaken, haven't touched this code in a while

**Comment by ajschorr** [comment]
I think the whole point of patchc1aed4ff8049c1de828fb744a181ed06aa124de4  was to pull it out of _cursor_get_c and do it at a higher level in selected cases. But if it doesn't drop the GIL, it seems pointless...

**Comment by ajschorr** [comment]
As long as I'm asking stupid questions, I'm going to double down. What's the point of calling 'preload' from the functions in lmdb/cffi.py? Does it drop the GIL in that case somehow? And here's another stupid one: why can't the preload() function in lib/py-lmdb/preload.h call Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS internally to alleviate the need for callers to do so? Then again, I do see one case in lmdb/cpython.c:trans_get() where mdb_get is also tucked inside the allow_threads block...

**Comment by ajschorr** [comment]
(which I'd probably address by having a preload_unlocked() version of the function that wraps it in Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS. Perhaps that could be a macro or a static inline function...

**Comment by jnwatson** [comment]
Yep I missed one.

**Comment by jnwatson** [comment]
While we're talking about this, is there any reason why preload takes an rc? Is it an attempt to avoid inlining?

**Comment by jnwatson** [comment]
Regarding calling preload in cffi town, cffi releases the GIL automatically every time it calls into C.

**Comment by jnwatson** [comment]
Fixed in https://github.com/jnwatson/py-lmdb/commit/394362e1a6943f666b7f5e1ecda5b83d079dcf2a

**Comment by dw** [comment]
It takes rc partly for safety and partly for convenience.. because there are so many calls to it littered everywhere. It definitely reads better when written more explicitly, but that opens the possibility of forgetting an `if()` and potentially reading from sometimes-uninitialized pointers and suchlike

**Comment by dw** [comment]
I seem to remember one case (around cursors?) where LMDB returning an error code could mean the mdb_val you pass in would have garbage in the output. It might reuse the struct you pass in to communicate internally between some functions

**Pull request merged**
