### PR TITLE
Add LMDB_FORCE_SYSTEM modes to the builds

### LINKED ISSUE #92: Add CI tests for every build type.
Managed to break `LMDB_FORCE_SYSTEM` in the fix for 772767fcf95419ca5ff2d97f122126cb7b68decf, spotted by Jos in #88.

Ensure Travis CI config tries every build type before returning success

### PR DESCRIPTION
**Pull request by astronouth7303**
Fixes #92

### CODE REVIEW

**Comment by astronouth7303** [comment]
Hm, is the version of lmdb in apt significantly different from the one you test with?

**Comment by astronouth7303** [comment]
Yes, the version in `lib` is 0.9.22, but the version Travis installs from apt is 0.9.10.

**Comment by astronouth7303** [comment]
I'm not sure Windows+System Library makes sense? Unless you mean "install [LMDBWindows](https://github.com/ChristophePichaud/LMDBWindows) separately and build from that".

**Comment by dw** [comment]
Yes, maybe Windows+library is skippable.. most users there expect a prebuilt solution

**Comment by astronouth7303** [comment]
A maintainer's opinion on this would be really great.

**Comment by dw** [comment]
I haven't tuned in for a while, but I believe upstream LMDB only have a single stable branch. In that case, the latest version should be bundled with py-lmdb and we should just try building against whatever is available in the CI VM already, or if nothing is available, simply try against any old version. Really the original ticket is about ensuring setup.py works.

Thanks a ton for looking at this -- my hands are completely full on another project just now.

**Comment by astronouth7303** [comment]
In general, most projects don't merge PRs that break their CI.

In the course of implementing #92, I have uncovered a new bug.

The two popular options are:
* Fix the new bug (likely in a new bug/PR), merge that, then merge this
* Reconsider the original bug and if you really want that

Ideally, I would add the versions of LMDB that are shipped with major distributions to the matrix. However, Travis does not easily allow this. (The straightforward option is to refactor the CI to run inside a container, which is entirely manual and kinda annoying on Travis.)

So, as maintainers, would you rather add support for older versions (given that both Ubuntu and Debian--and presumably other distributions--ship older versions), drop support for compiling against the system library, or do the additional work (and build time) to expand the matrix to cover different versions of different distros?

**Pull request closed without merging**
