### PR TITLE
Solaris needs ```#include "python.h"``` as soon as possible #213

### PR DESCRIPTION
**Pull request by jcea**
Bug #213 .

### CODE REVIEW

**Comment by jnwatson** [comment]
Thanks! I'll spin a release later this weekend.

**Comment by jcea** [comment]
@jnwatson, PYPI is still distributing a "lmdb" module without this fix. Maybe you got distracted before publishing release with this fix in it?. It is annoying to need to patch my servers manually every time I reprovision them :-).

Thanks for your time and effort!

**Comment by jnwatson** [comment]
Yep. I’ll get on that tonight. Thanks for the reminder.

**Comment by jnwatson** [comment]
Version 0.98 has been released.

**Pull request merged**
